#!/bin/sh -e

# You're from ohio, stop denying it.
test -d $HOME/ohio || (echo Ohio doesnt exist at $HOME/ohio && exit 1)

cd $HOME/ohio

# first compile rc. Yes this is redundant.
(
	cd rc
        ./configure --with-readline
        make
)


# symlink over ohio's mr, vcsh, and rc. Make sure symlinks are
# absolute and relative in the right places.
(
	cd $HOME
        mkdir -p bin
        cd bin
        test -L vcsh || ln -s $HOME/ohio/vcsh/vcsh vcsh
        test -L rc || ln -s $HOME/ohio/rc/rc rc
        test -L mr || ln -s $HOME/ohio/myrepos/mr mr
)

# symlink over myrepos config
(
	cd $HOME
        test -L .mrconfig || ln -s $HOME/ohio/mrconfig .mrconfig
)

cd $HOME
./bin/mr update
